### ISSUE TITLE
source source_env.sh  bash: ./install/setup.bash: 没有那个文件或目录

### ISSUE THREAD

**Issue by ooswald216** [L5Player/AutoDriving-Planning-Control-Algorithm-Simulation-Carla#1]
1、最后一句是什么意思？刷新环境变量吗？
2、我需要把这个东西放进catkin_workspace里面编译吗？

**Comment by LadissonLai** [comment]
你使用colcon build编译之后，就会有./install/setup.bash文件了

**Comment by L5Player** [comment]
1、上面的几个环境变量根据自己环境的路径更改；
2、bash: ./install/setup.bash 是用项目编译生成的运行环境覆盖底层ros环境，如果没有编译项目没有这个文件，编译项目后就会生成这个脚本

**Comment by ooswald216** [comment]
> 你使用colcon build编译之后，就会有./install/setup.bash文件了

请问怎么用ROS2编译啊？colcon build --packages-select <name-of-pkg> 这样指定包名吗？请指点一二
